name: Variant-Annotation
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - bc=1.07.1
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.12.7
  - cairo=1.16.0
  - coreutils=9.2
  - curl=7.87.0
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freebayes=1.3.6
  - freetype=2.12.1
  - gettext=0.21.1
  - giflib=5.2.1
  - graphite2=1.3.13
  - harfbuzz=6.0.0
  - htslib=1.17
  - icu=70.1
  - jpeg=9e
  - k8=0.2.5
  - keyutils=1.6.1
  - krb5=1.20.1
  - lcms2=2.14
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libcups=2.3.3
  - libcurl=7.87.0
  - libdeflate=1.13
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libglib=2.74.1
  - libgomp=12.2.0
  - libiconv=1.17
  - libnghttp2=1.51.0
  - libnsl=2.0.0
  - libpng=1.6.39
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.4.0
  - libuuid=2.32.1
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libzlib=1.2.13
  - minimap2=2.24
  - ncurses=6.3
  - nextflow=22.10.6
  - openjdk=17.0.3
  - openssl=1.1.1t
  - parallel=20230322
  - pcre2=10.40
  - perl=5.32.1
  - pip=23.0.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - python=3.11.0
  - readline=8.2
  - samtools=1.16.1
  - setuptools=67.6.0
  - snpeff=5.1
  - tabixpp=1.1.0
  - tk=8.6.12
  - tzdata=2023b
  - vcflib=1.0.3
  - vcftools=0.1.16
  - wheel=0.40.0
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - biopython==1.81
    - numpy==1.24.2
    - pyvcf3==1.0.3
